### ISSUE TITLE
Checklist 

### ISSUE THREAD

**Issue by shivangik11** [shivangik11/ATLAS-ios-Fall-22#2]
## Application Design: Checklist

- [X] Complete all the readings provided.
- [X] Finalize the topic for the Application design.
- [X] Go for relevant tutorials if possible.
- [X] Start looking for similar applications and their implementations.
- [X] Work on Xd prototype.
- [x] Start coding with the first page UI.
- [x] First page working.
- [ ] Code of Second Page UI.
- [ ] Second Page Working.
- [ ] Discuss with the professor.

## Learnings
I have started coding with the first page, and while I am not entirely certain that it will turn out in accordance with my expectations, I am a little bit thrilled to code, and I am really looking forward to implementing it as a functional model. 
My idea has not undergone a fundamental transformation, but I have made some alterations to its structure. The core idea remains the same; it combines the process of making something with the preparation for travels and vacations. I have improved upon the original concept by including additional elements. 
As I am still in the very beginning stages of the coding process, there is currently nothing extremely relevant to the application, so the most difficult aspect for me is to understand swift Ui and basic features of it. But coming up with an idea was also a challenge for me. I didn't want to set my sights too high because I was afraid that I wouldn't be able to reach them. Instead, I wanted to find something that I could learn from and that would assist me in achieving my long-term objectives.

![Web 1366 – 1](https://user-images.githubusercontent.com/89596201/195478632-49cb1b5f-dba5-4fd4-ac7a-022d1347877d.png)

**Comment by zef** [comment]
Hey Shivangi! Your XD designs look like a good start and would be a great exercise to recreate in SwiftUI. Are you still planning on focusing on packing lists, or are you thinking of trying to implement other sections like in your mockups?

I looked at your mapping repo a bit too and was wondering if you're planning on using that in your "Places to Visit" or something like that.

Could you change this to be just the repo name itself rather than the full path on GitHub? Also, I'm not sure if you want to add your `application-design` repo there too.
https://github.com/shivangik11/ATLAS-iOS-Fall-22/blob/b85de3d379d5fe0eaabc0154f48f373f5c0beebc/config.yml#L8

And do you have another repo where you are going to have your application code for this, or is that going to be in your `application-design` repo?

Thanks!

**Comment by shivangik11** [comment]
My focus is going to be the list first, if I can go ahead and work as my mockup would try to do that.
Mapping was something I was trying to work on, I am still not sure what to inculcate and what not to, but will try to put as much as possible or as much I have learned during the semester.

application design is going to be the repo where I am going to include my code as well.
